### ISSUE TITLE
I appreciate what you have done

### ISSUE THREAD

**Issue by bnusbick** [drandyhaas/Haasoscope#21]
Hi Andy,
I watched Dave's video review of your product, and while I generally like his blog, I think he was much too hard on you.  He spent most of the time complaining about the schematic and complaining why his high-end probes don't work with your board.  The probes I bought with the scope fit fine, and I am certainly not going to be reproducing your board.  Also, he spent a lot of time criticizing the installation and interface, which he could have avoided by reading your instructions.

What I really like about your product is:
  It works on Lubuntu.
  You have been very responsive to comments.
  The GUI is in python so I can tweak it if desired.
  Since I am also interested in FPGAs, I can see an example of a working project.

I do seem to have a trouble triggering when waiting for an event, but maybe that is something I am doing wrong, since no one else is reporting this issue.

I do hope you continue to have an interest in it and those of us who bought it.

**Comment by drandyhaas** [comment]
Thanks for the nice message!
