### ISSUE TITLE
Incorporate hints from eevblog

### ISSUE THREAD

**Issue by ooxi** [drandyhaas/Haasoscope#23]
[eevblog on YouTube](https://www.youtube.com/watch?v=R_Ud-FxUw0g) has done an improved version of the current schematics. Would it be possible to incorporate those improvements in this repository?

**Comment by drandyhaas** [comment]
I already uploaded an improved schematic to this github a couple days ago... Take a look please.

**Comment by ooxi** [comment]
Nice work, thank you!
