### ISSUE TITLE
OLED doesn't show anything past boot screen

### ISSUE THREAD

**Issue by tedder** [drandyhaas/Haasoscope#3]
See picture for my OLED install. It's on the leftmost pins, leaving three pins on the right unconnected. That appears to match what's in the documentation.

![2018-05-01 14 02 24](https://user-images.githubusercontent.com/97914/39493653-8693d4f0-4d48-11e8-9367-cbce7642879d.jpg)

It shows that (slightly odd) boot image and doesn't change. Tried powering off and back on, no change.

**Comment by drandyhaas** [comment]
Once you readout an event, it should show that event (from the selected channel). Are you reading out events?

**Comment by tedder** [comment]
I haven't connected it (still installing Qt dependencies). I assumed it would work when standalone.

**Comment by drandyhaas** [comment]
No, it does nothing until you read out events. I'll clarify this in the guide.
