### ISSUE TITLE
Help, hw design files

### ISSUE THREAD

**Issue by luftek** [drandyhaas/Haasoscope#30]
**What are you trying to do?**
I want to inspect hw design files. Which Eagle version to download/install. It should probably support more than 2 layers, I suppose.

**What is your OS?**
Windows 10

**Comment by drandyhaas** [comment]
Hi,
Any recent eagle version will be fine. I have 9.2.0 installed currently.
I have some free licence for academic that lets me make a 4-layer board. But I think you can edit the existing files without a license even.

**Comment by luftek** [comment]
Yes, free version can open and show current 4 layer design.
