### ISSUE TITLE
c# / .net communication

### ISSUE THREAD

**Issue by percramer** [drandyhaas/Haasoscope#34]
Hi,

i was wondering if anybody ever attempted to communicate with a Haasoscope through c#? I am currently using a lab nation scope in combination with c#, but i need more channels.

**Comment by drandyhaas** [comment]
Hi,
I'm not aware of anyone doing it yet, but as long as you can talk from c#
to uart serial, you can talk to the Haasoscope. Example simple commands to
talk to the scope over serial are in software/serial_read.py.
You could also write some c# to python pipe to send commands crom c# to the
usual Haasoscope python program and grab the data back.
Good luck!
