### ISSUE TITLE
Python 2 EOL coming end of this year

### ISSUE THREAD

**Issue by Ivoz** [drandyhaas/Haasoscope#44]
https://pythonclock.org/

I see you've released the software platform for your scope on Python 2. Python 2 is about to be un-maintained. Nobody should be being asked to install it for new products for a few years now!

Libraries like Numpy & Scipy will no longer make new releases for Python 2 either.
https://python3statement.org/

Fortunately all the libraries you require are easily python 3 compatible. Maybe this year you would be able to ask the CompSci department at your uni if there are students who would like to volunteer to help you port it to Python 3. This could essentially be a great real-world exercise for them.

Finally, they might then be able to help you package the software as a self-contained executable/installer. For those (like EEVBlog Dave) who prefer to just "use" their hardware.

They could probably help you work on your git organisation as well. I would already suggest separating the hardware design, firmware, desktop software & android software sides of this project into 4 different repositories.

I would normally like to help but am hesitant about dropping money for the board at this time.

I could see from Dave's mailbag review that software is one part where you absolutely failed make any positive impression, so I wanted to give some unwarranted suggestions. Good luck with this project.

**Comment by drandyhaas** [comment]
Another kind contributor did the port to Python3. It's now in branch "python35". It seems to work, though I haven't tested it fully. 
On Ubuntu Linux you need to install:
sudo apt-get install git python3 python3-serial python3-numpy python3-matplotlib python3-scipy python3-pyside
