### ISSUE TITLE
Can't scan JTAG chain. Error code 87

### ISSUE THREAD

**Issue by polachz** [drandyhaas/Haasoscope#45]
Hallo.

I have tried to update firmware into my Haasoscope board (V 8.81) I use Windows version and the Blaster driver provided by you to avoid the BSOD.

I have connected just USB blaster and it's cable to the board. The power led hac correct Red light.

Then I fire 

s:\Haas\Haasoscope\max10_adc_firmware>c:\intelFPGA_pro\18.1\qprogrammer\bin64\quartus_pgm.exe --bgp -m jtag -o "p;output_files/serial1.pof"

And then I have got this error on the command line:

Can't scan JTAG chain. Error code 87

When I try to use GUI version, then the Test JTAG Chain produces additional info
Error: JTAG chain problem detected
Error: No device detected. Detected 1's at TDI pin.

What can be wrong, please?

**Comment by drandyhaas** [comment]
You also need to power the board through the normal usb connection (or other 5V source). The power through the jtag cable is not sufficient.

**Comment by polachz** [comment]
Ok, thank you for the explanation. I'll try firmware update again today afternoon. Maybe you can improve the guide by this piece of information? I Thought about additional power, but was not sure if it si necessary ot not and if it/s not risky.

**Comment by drandyhaas** [comment]
OK, clarified the guide. Thanks!

**Comment by polachz** [comment]
I can confirm that additional power source solves the problem. Thank you for quick support!
