### ISSUE TITLE
Glitchy signal showing 'spikes'

### ISSUE THREAD

**Issue by anj1** [drandyhaas/Haasoscope#47]
I always seem to get 'glitches' or 'spikes' when looking at a signal. I've attached pictures to show what I mean:

[1 kHz sine wave](https://imgur.com/IEqemzP)

[Same signal, zoomed in more](https://imgur.com/Vr5W4GP)

[Same signal, zoomed in much more, showing the glitch in detal](https://imgur.com/P8J0Pvz)

Looking at it with another oscilloscope, the signal is fine. The glitches seem to happen during zero-crossings, irrespective of the signal frequency. For a 10 kHz signal, for example, I also get glitches around the zero crossings.

I also get the glitches in both DC and AC coupling mode.

**Comment by anj1** [comment]
Additionally, I only get the glitches on channel 0, not on any of the other channels.

**Comment by drandyhaas** [comment]
Strange. Can you try changing the DC offset of the other channels (move them up or down) and see if that affects the spikes on channel 0?
