### ISSUE TITLE
Mac install steps

### ISSUE THREAD

**Issue by tedder** [drandyhaas/Haasoscope#5]
Figure this might be handy in the doc:

```
brew install cartr/qt4/qt@4 cartr/qt4/pyqt@4 sip --without-python
pip2 install pyserial numpy matplotlib PySide Qt.py scipy
```

**Comment by drandyhaas** [comment]
What's that for exactly? What platform?

**Comment by tedder** [comment]
Sorry- it's for MacOS (10.13.*, but probably most recent versions). Those are the prereqs to use HaasoscopeDraw.py.

**Comment by drandyhaas** [comment]
Ah, cool. Added to guide.
