### ISSUE TITLE
File Capture with Qt GUI

### ISSUE THREAD

**Issue by Jeffbeck67** [drandyhaas/Haasoscope#57]
Hi,

Can you confirm the file structure generated on with the Qt interface as follows:

![Capture](https://user-images.githubusercontent.com/57655100/72240203-c2053600-3626-11ea-90fa-9bf758792f75.PNG)

**Comment by drandyhaas** [comment]
Correct, except the Unix time should have at least ms precision. It's a float. It seems you're not displaying digits after the decimal point?

**Comment by Jeffbeck67** [comment]
Correct!
Now it's OK. This could be added in the guide later on.
Thanks.
![Capture](https://user-images.githubusercontent.com/57655100/72302646-143d6a00-36ae-11ea-97a9-db62cf8c4aa3.PNG)
