### ISSUE TITLE
ADC Accuracy

### ISSUE THREAD

**Issue by Jeffbeck67** [drandyhaas/Haasoscope#58]
Hello,
I've been measuring the precision of the ADCs that for 8 bits was supposed to be perfect and it seems not.
Protocol: 250 kHz triangle, 8,2Vpkpk to have full swing.  Recording 512 Samples and cropping the data to have 1 output code increase per sample.
![image](https://user-images.githubusercontent.com/57655100/72661223-2eaf7480-3a1b-11ea-83a8-19b5ad4d7014.png)

I get up to 4 bits error. Is that possible ? 
![image](https://user-images.githubusercontent.com/57655100/72661210-01fb5d00-3a1b-11ea-92a3-f9fd63e5f446.png)

I'm not familiar with ADC testing and my terminology is likely wrong.

**Comment by drandyhaas** [comment]
First of all, that doesn't look terrible.
But how many bits is your function generator? 
Also, you could try smaller voltage swing, or slower sleep, to see if that changes things.

**Comment by Jeffbeck67** [comment]
Usual question of test devices vs DUT. Frankly I don't know. It's given for 12 bit.
Below a 40 us ramp that is RC filtered. significantly better. 
that was a good lesson, I did not expect a 8 bit ADC to be so tricky to test.
![image](https://user-images.githubusercontent.com/57655100/72673736-f73fd700-3ab1-11ea-8a3f-b06758253cb3.png)
