### ISSUE TITLE
New 3d case for the Haasoscope

### ISSUE THREAD

**Issue by KevinOConnor** [drandyhaas/Haasoscope#79]
This is not an issue; it is notification of a 3d printable case that I designed for the Haasoscope.  Let me know if there is a better place to discuss topics like this.

I designed a case for the Haasoscope: https://github.com/KevinOConnor/hcase (and https://www.printables.com/model/356793-haasoscope-case ).  The haasocope board can "click" into the bottom of this case and the top of the case can also "click" into the bottom.

This case also encloses all the pins (only the bmc connectors extend from the case).  There are openings for most ports, including the usb port of the "hi speed usb module".

-Kevin

**Comment by drandyhaas** [comment]
Thanks!
